---
- hosts: all
  connection: ssh

  tasks:
    - name: Install a httpd server
      yum:
        name: httpd
        state: present

    - name: Start the httpd service
      service:
        name: httpd
        state: started

    - name: Create a file
      file:
        path: "/var/www/html/index.html"
        state: touch

    - name: Add some content to the file
      copy:
        dest: "/var/www/html/index.html"
        content: |
          <h1>HELLO EVERYONE THANKS FOR COMING TODAY ENJOY PANDAGO</h1>
